# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-py-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuber-py
  template:
    metadata:
      labels:
        app: kuber-py
    spec:
      containers:
        - name: kuber-py
          image: aparnahh/kuber-py:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-py-service
spec:
  selector:
    app: kuber-py
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
